version: "3.7"

services:
  app:
    image: decko1:latest
    command: docker_bundle
    ports:
      - 3000:3000
    volumes_from:
      - bundle
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
      MYSQL_DB: deck

  bundle:
    image: busybox
    volumes:
      - /bundle

  mysql:
    image: mysql:5.7
    volumes:
      - deckdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: deck

volumes:
  deckdb: